/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'deb' at '11/19/17 4:04 PM' with Gradle 2.10
 *
 * @author deb, @date 11/19/17 4:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
